site_name: A2AGC Dataset
site_url: https://demo.cns.iu.edu/agc2
site_description: A2AGC Dataset documentation
site_author: CNS & Regenstrief Institute

repo_url: https://github.com/cns-iu/a2agc-dataset/

# Set edit_uri to "" to remove the "Edit on GitHub" link
# edit_uri: ""

use_directory_urls: false

nav:
  - About: index.md
  - Change Log: CHANGELOG.md
  - Dataset:
  #  - Overview: dataset/index.md
  #  - Data Access Requirements: dataset/access.md
    - '<i class="fa fa-link" aria-hidden="true"></i> Schema Browser': schema/index.html
    - '<i class="fa fa-link" aria-hidden="true"></i> ER Diagram': schema/relationships.html
    - '<i class="fa fa-table" aria-hidden="true"></i> deaths': dataset/tables/table-deaths.md
    - '<i class="fa fa-table" aria-hidden="true"></i> diagnoses': dataset/tables/table-diagnoses.md
    - '<i class="fa fa-table" aria-hidden="true"></i> ems_incidents': dataset/tables/table-ems_incidents.md
    - '<i class="fa fa-table" aria-hidden="true"></i> encounters': dataset/tables/table-encounters.md
    - '<i class="fa fa-table" aria-hidden="true"></i> incarcerations': dataset/tables/table-incarcerations.md
    - '<i class="fa fa-table" aria-hidden="true"></i> incarcerations_weekly': dataset/tables/table-incarcerations_weekly.md
    - '<i class="fa fa-table" aria-hidden="true"></i> labs': dataset/tables/table-labs.md
    - '<i class="fa fa-table" aria-hidden="true"></i> medications': dataset/tables/table-medications.md
    - '<i class="fa fa-table" aria-hidden="true"></i> procedures': dataset/tables/table-procedures.md
    - '<i class="fa fa-table" aria-hidden="true"></i> referrals': dataset/tables/table-referrals.md
    - '<i class="fa fa-table" aria-hidden="true"></i> rollup1': dataset/tables/table-rollup1.md
  #  - Validation Results: dataset/validation.md
  #- Source Code:
  #  - Dataset Generation: dataset/workflow.md
  #  - Data Analytics: analytics.md
  - Visualizations:
  #  - Getting Started: examples/getting_started.md
    - Geographic Map of Opioid Deaths: examples/vis-geomap-opioid-deaths.md
    - Demographic Comparison of Opioid Deaths: examples/visualization1.md
    - Heatmaps of Deaths with Substance: examples/visualization4a.md
    - Heatmaps of Substance Proportions at Death: examples/visualization4.md

plugins:
  - search
  - macros

# Module defining additional variables/macros for jinja2 processing
python_module: mkdocs_macros_extras

extra:
  source_prefix: 'https://github.com/cns-iu/a2agc-dataset/blob/develop/'

  # MkPDFs doesn't work with readthedocs theme and
  # the generated schema html. So for now, we'll
  # turn PDF generation off.
  # TODO: Report bugs to mkpdfs-mkdocs repo.
  # - mkpdfs:
  #     output_path: pdf/a2agc-documentation.pdf

theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True
  - footnotes
