site_name: A2AGC Dataset
site_url: https://demo.cns.iu.edu/agc2
site_description: A2AGC Dataset documentation
site_author: CNS & Regenstrief Institute

repo_url: https://github.com/cns-iu/a2agc-dataset/

# Set edit_uri to "" to remove the "Edit on GitHub" link
# edit_uri: ""

use_directory_urls: false

nav:
  - About: index.md
  - Dataset:
    - Overview: dataset/index.md
    - Data Access Requirements: dataset/access.md
    - '&#x1F517; Schema Browser': schema/index.html
    - ER Diagram: schema/relationships.html
    - Data Tables: dataset/tables.md
    - Validation Results: dataset/validation.md
  - Source Code:
    - Dataset Generation: dataset/workflow.md
    - Data Analytics: analytics.md
  - Examples:
    - Getting Started: examples/getting_started.md
    - Geographic Map of Opioid Deaths: examples/vis-geomap-opioid-deaths.md
    - '# Opioid Prescriptions and Death Correlation': examples/n-opioid-death/index.md

plugins:
  - search

  # MkPDFs doesn't work with readthedocs theme and 
  # the generated schema html. So for now, we'll
  # turn PDF generation off.
  # TODO: Report bugs to mkpdfs-mkdocs repo.
  # - mkpdfs:
  #     output_path: pdf/a2agc-documentation.pdf

theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True
