site_name: A2AGC Dataset
site_url: https://node.cns.iu.edu/client/a2agc/
site_description: A2AGC Dataset documentation
site_author: Cyberinfrastructure for Network Science Center & Regenstrief Institute

repo_url: https://github.com/cns-iu/a2agc-dataset/

# Set edit_uri to "" to remove the "Edit on GitHub" link
# edit_uri: ""

use_directory_urls: false

nav:
  - About: index.md
  - Visualizations:
    # - Getting Started: examples/getting_started.md
    - Opioid Death Trajectories: examples/visualization2.md
    - Geographic Map of Opioid Deaths: examples/visualization5.md
    - Age group and gender of accidental drug overdose deaths and population in Marion County 2010-2018: examples/bar-visualization/page.md
    # - Heatmaps of Deaths with Substance: examples/visualization4a.md
    - Heatmaps of Substance Proportions at Death: examples/visualization4.md
    - Touchpoints/Opioid Death Trajectories: examples/visualization2.md
  - Dataset:
    # - Overview: dataset/index.md
    # - Data Access Requirements: dataset/access.md
    - Schema Browser: schema/index.html
    - ER Diagram: schema/relationships.html
    - Tables:
      - Deaths: dataset/tables/table-deaths.md
      - Diagnoses: dataset/tables/table-diagnoses.md
      - Ems Incidents: dataset/tables/table-ems_incidents.md
      - Encounters: dataset/tables/table-encounters.md
      - Incarcerations: dataset/tables/table-incarcerations.md
      # - Incarcerations Weekly: dataset/tables/table-incarcerations_weekly.md
      - Labs: dataset/tables/table-labs.md
      - Medications: dataset/tables/table-medications.md
      - Procedures: dataset/tables/table-procedures.md
      - Referrals: dataset/tables/table-referrals.md
      # - Rollup1: dataset/tables/table-rollup1.md
  #  - Validation Results: dataset/validation.md
  #- Source Code:
  #  - Dataset Generation: dataset/workflow.md
  #  - Data Analytics: analytics.md
  - Change Log: CHANGELOG.md

plugins:
  - search
  - macros:
      module_name: mkdocs_macros
  # MkPDFs doesn't work with readthedocs theme and
  # the generated schema html. So for now, we'll
  # turn PDF generation off.
  # TODO: Report bugs to mkpdfs-mkdocs repo.
  # - mkpdfs:
  #     output_path: pdf/a2agc-documentation.pdf

markdown_extensions:
  - toc:
      permalink: True
  - footnotes

theme:
  name: ivory

extra_css:
  - css/extra.css

extra:
  source_prefix: 'https://github.com/cns-iu/a2agc-dataset/blob/develop/'
